"""Micro REST-Style API Server.

This is a simple HTTP server, specialised to the delivery of a REST-like API
instead of a general HTTP server. The design, and the use of the `asyncio`
library, is inspired by the [MicroPython HTTP
Server](https://github.com/erikdelange/MicroPython-HTTP-Server) by Erik de
Lange. This library uses a roughly similar structure for the core of the
`asyncio` drivers, and especially in the `HTTPResponse` class. Differences
include

* A more object-oriented design of the call/response handler, made easier this
library is _not_ a general HTTP server. For instance Python `getters` and
`setters` are used where possible for input validation, and the central API
response is based on the `APICall` abstract base class

* A more explicit validation of input from the network layer, especially in the
assumption that all input is by default hostile. This library should serve as an
example of best-practice in protocol handling; at least in the slightly resource
constrained environment of MicroPython.

Notes
-----

1. This implementation is principally a teaching library, so the documentation
should be at least as important as the 'code'. Where possible all algorithms and
implementation techniques should also be explained as fully as possible, or at
least linked to reference standards/implementations.

2. All documentation should be attached to the relevant code wherever possible,
and should be formatted according to the [NumPy
Documentation](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst
.txt) docstring  standard. Documentation is generated by the
[pdoc](https://pdoc3.github.io/pdoc/) library, and should be rebuilt before
committing any code. Use the `hook.sh` script as a pre-commit hook for `git`, or

    >  pdoc --html --force --output-dir doc .

    in the source directory

3. For consistency, all code should also be in the format standardised by the
[Black](https://github.com/psf/black) library. This makes it easier to
co-ordinate external code and documentation with the implementation documented
here.

Example
-------

### Creating the Application `main` loop

This module assumes that the lower-level networking layers are already in place:
if you are using MicroPython that may mean additional work. You will also need a
copy of the `asyncio` library (or `uasyncio` in MicroPython. This can be
imported conditionally as

```python
   # Import the Asynchronous IO Library,
   # preferring the MicroPython library if
   # available
   try:
     import uasyncio as asyncio
   except ImportError:
    import asyncio
```

Once the network and asynchronous I/O library is available, create an instance
of the `urest.http.server.RESTServer` class from the `urest.http.server` module

```python
  from urest.http import RESTServer

  app = RESTServer()
```

The application `app` above can now we passed to an appropriate event loop of
the `asyncio` library, for instance as

```python
  if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(app.start())
    loop.run_forever()
```

Putting the above together, a minimal main loop looks something like

```python
  # Import the Asynchronous IO Library
  try:
    import uasyncio as asyncio
  except ImportError:
    import asyncio

    from urest.http import RESTServer

    app = RESTServer()

    if __name__ == "__main__":
      loop = asyncio.get_event_loop()
      loop.create_task(app.start())
      loop.run_forever()
```

Licence
-------

This module, and all included code, is made available under the terms of the MIT
Licence

> Copyright 2022-2023, David Love

> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
